# Generated by Django 3.0.5 on 2020-09-24 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0002_auto_20200923_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
